name: wi_ogsusu
description: wi_ogsusu

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  dio: ^1.0.0
  device_info: ^0.2.1
  url_launcher: ^3.0.3
  json_annotation: ^1.2.0
  shared_preferences: ^0.4.3
  path_provider: ^0.4.1
  video_player: ^0.7.2
  image_picker: ^0.4.7
  fluro: ^1.3.4
  connectivity: ^0.3.2
  carousel_slider: ^0.0.7
  transparent_image: ^0.1.0
  simple_permissions: ^0.1.9
  sqflite: ^0.12.2+1
  crypto: ^2.0.6
  unicorndial: ^1.1.5
  chewie: ^0.8.0
  flutter_webview_plugin: ^0.3.0+2
  flutter_calendar_carousel: ^1.2.2
  flushbar: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^1.5.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - res/values/strings_en.arb
    - res/values/strings_zh.arb
    - res/img/icon_ogsusu.jpg
    - res/img/icon_ogsusu.png
    - res/img/splash.jpg
    - res/img/hold.jpg
    - res/img/hold1.jpg
    - res/img/american_football_24px.png
    - res/img/basketball_24px.png
    - res/img/football_24px.png
    - res/img/icon_wwe_64.png
    - res/img/icon_nba_64.png
    - res/img/icon_nfl_64.png
    - res/img/icon_ufc_64.png
    - res/img/icon_mlb_64.png
    - res/img/icon_mls_64.png
    - res/img/icon_nhl_64.png
    - res/img/icon_f1_64.png
    - res/img/icon_tennis_64.png
    - res/img/icon_golf_64.png
    - res/img/icon_indy_64.png
    - res/img/icon_nascar_64.png
    - res/img/icon_sad_80.png
    - res/img/bg_my_header.jpg
    - res/img/avatar_hold.png
    - res/img/bg_my_header1.jpg
    - res/img/bg_my_header2.jpg
    - res/img/bg_my_header3.jpg
    - res/img/bg_my_header4.jpg
    - res/img/icons8_card_security_96.png
    - res/img/icons8_cheap_96.png
    - res/img/icons8_vip_96.png
    - res/img/icons8_calendar_plus_96.png
    - res/img/event_1.jpg
    - res/img/banner_check_in.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
